---
name: Build and Deploy auberguets-webapp to GitHub Pages
on:
  push:
    branches: [ prod ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

#      - name: Test
#        run: npm run test

      - name: Deploy
        run: |
          git config --global user.name 'Marceron Quentin'
          git config --global user.email 'proquentinmarce@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy